### ISSUE TITLE
Generating XAML

### ISSUE THREAD

**Issue by seankearon** [Dzoukr/Fue#1]
Hey - this is a great library, I really like it and would like to use it to generate some XAML.  Only trouble is, tags get output in lowercase.  For example, 

`<StackPanel>...</StackPanel>`

becomes

`<stackpanel>...</stackpanel>`

Is there a way to prevent this?

**Comment by Dzoukr** [comment]
Hi @seankearon,

I am happy that you are using this library and like it. Thanks for this issue report - now (in [version 1.1.0](https://github.com/Dzoukr/Fue/releases/tag/v1.1.0)) this should be fixed and original tags case should be kept.

Thanks,
Roman

**Comment by seankearon** [comment]
That's fantastic, thank you. :)
