### ISSUE TITLE
Allow passing records/maps to functions

### ISSUE THREAD

**Issue by schwarzeszeux** [Dzoukr/Fue#18]
First of all, let me say thank you for creating this library.

I wanted to be able to pass more than just primitives to functions.
Unfortunately this was not possible with the current parser implementation.

Because it serves a need for me, I went ahead and reimplemented TemplateValue-Parser with FParsec.

Now the question is, are you interested in a PR?
If you are, I'd try and get the code cleaned up and open one.

Among other things, I'm using this to render sub-templates like so:

```
init
|> add "render" fromFile
|> fromFile "..."
```
```
<h1>TemplateTest</h1>
{{{render("sub.html", {
    content = "Content Test"
    foo = "bar"
})}}}
```

in sub.html I'm now able to access `content` and `foo`

You can find the for here: https://github.com/schwarzeszeux/Fue

ps: I also had to migrate the project to .net6.0

**Comment by Dzoukr** [comment]
Hi @schwarzeszeux, I'd be happy for any help that would make this library better. 🙏

**Comment by schwarzeszeux** [comment]
I've created a PR, let me know what you think - but do not merge yet as I've left some debug-code inside in case I need to make adjustments.

Better is always a matter of perspective - I haven't done any benchmarks on the new parser, it might be significantly slower ;)
