### ISSUE TITLE
Support DotNetCore

### ISSUE THREAD

**Issue by ibnuda** [Dzoukr/Fue#2]
Hello, would you mind to add DotNetCore support? Or, what can I help you to add this functionality?

**Comment by Dzoukr** [comment]
Hi @ibnuda, thanks for the offer, I expected someone will request DotNetCore one day. :) I am just thinking loud: Shouldn´t we wait for F# 4.1 and upgrade this library to .NETStandard?

**Comment by ibnuda** [comment]
Alright, I agree with you.

One thing, though. I just found out that this library has HtmlAgilityPack as its dependency. And HAP itself doesn't support .NETStandard.
Do you have any plan about it?

**Comment by Dzoukr** [comment]
You are right. I´ll try to find out plans for moving HAP into .NETStandard. Or I could probably use one of existing .NET Core ports of HAP like [HtmlAgilityPack.NetCore](https://www.nuget.org/packages/HtmlAgilityPack.NetCore)

I have quite a lot of tests so moving to another lib should not be big problem.

**Comment by ibnuda** [comment]
Nice. And I'll close this issue.

Thanks.

**Comment by Dzoukr** [comment]
Ok, thanks. So once F# 4.1 will be out, I`ll start with Fue migration to .NETStandard.

**Comment by Dzoukr** [comment]
Hi @ibnuda - Fue is now under .NET Standard 2.0 :)

**Comment by ibnuda** [comment]
Thanks!
