### ISSUE TITLE
Is the a way to specify text with  spaces

### ISSUE THREAD

**Issue by rkosafo** [Dzoukr/Fue#4]
Given
    
     let x = parseTemplateValue """ {{{ now() |> fmtDate "MMMM/yyyy"}}} """
     let y = parseTemplateValue """ {{{ now() |> fmtDate "MMMM yyyy"}}} """   

where the data is defined as

    init
    |> add "now" (fun () -> DateTime.Now)
    |> add "fmtDate" (fun (fmt:string) (x:DateTime) -> x.ToString (fmt))

`x` is treated as a function (`fmtDate`) call with two parameters (the string `MMMM/yyyy` and the `now` function call)

`y` however is treated as a function with three parameters. The `MMMM yyyy` appears as two different parameters instead of just one. This then causes the templating to fail.

Is this a bug?
How does one specify text with spaces to get `y` to return something valid?

**Comment by Dzoukr** [comment]
Hi @rkosafo, thanks for report. Yes, this is bug, I got it in pipeline already . I`ll let you know once fixed.

**Comment by Dzoukr** [comment]
Fixed in v1.3.0
