### ISSUE TITLE
<| in template "closing tag"

### ISSUE THREAD

**Issue by rkosafo** [Dzoukr/Fue#6]
Given
    init
    |> add "multiply" (fun (x: string) -> (int x) * 2)
    |> fromText """ {{{multiply <|  '2'}}}"""
    
The output is `{{{multiply <| '2'}}}></| '2'}}}>`

**Comment by Dzoukr** [comment]
Pipe backward operator is not supported - only pipe forward one `|>`. I should add this to documentation.
